ARG NODE_VERSION

FROM node:${NODE_VERSION} AS build

COPY . .

RUN npm ci && \
    npm run check && \
    npm run build

FROM node:${NODE_VERSION}-alpine AS runtime

COPY --from=build /dist ./

ARG PORT

ENV PORT=${PORT}

EXPOSE ${PORT}/tcp

ARG FIREBASE_API_KEY

ENV FIREBASE_API_KEY=${FIREBASE_API_KEY}

ARG FIREBASE_PROJECT_ID

ENV FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}

ARG FIREBASE_MESSAGING_SENDER_ID

ENV FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID}

ARG FIREBASE_APP_ID

ENV FIREBASE_APP_ID=${FIREBASE_APP_ID}

ENTRYPOINT ["node", "index.js"]
